module

public import QITBench.Base

/-!
# Holevo Bound for the Classical Capacity of `n` Qubits

The mutual information is now computed from an explicit ensemble and POVM.  The
Holevo inequality and the `n`-qubit entropy cap are part of the theorem target,
not assumptions handed to the theorem.
-/

@[expose] public section

namespace QITBench.HolevoBoundClassicalCapacityNQubits

open scoped BigOperators ComplexOrder MatrixOrder

noncomputable section

abbrev NQubitBasis (n : ℕ) : Type :=
  Fin n → Fin 2

noncomputable def log2 (x : ℝ) : ℝ :=
  Real.log x / Real.log 2

def IsProbabilityDistribution {ι : Type*} [Fintype ι]
    (p : ι → ℝ) : Prop :=
  (∀ x : ι, 0 ≤ p x) ∧ ∑ x : ι, p x = 1

/-- Spectral von Neumann entropy, zero outside the PSD cone. -/
noncomputable def vonNeumannEntropyMatrix {d : Type*} [Fintype d] [DecidableEq d]
    (rho : CMatrix d) : ℝ := by
  classical
  exact if h : rho.PosSemidef then
    -∑ i : d, h.1.eigenvalues i * log2 (h.1.eigenvalues i)
  else
    0

noncomputable def averageStateMatrix {ι d : Type*} [Fintype ι] [Fintype d] [DecidableEq d]
    (p : ι → ℝ) (rho : ι → State d) :
    CMatrix d :=
  ∑ x : ι, (p x : ℂ) • (rho x).matrix

/-- Joint distribution generated by preparing `rho x` with probability `p x` and measuring `M`. -/
noncomputable def jointProbability {ι y d : Type*}
    [Fintype ι] [Fintype y] [DecidableEq y] [Fintype d] [DecidableEq d]
    (p : ι → ℝ) (rho : ι → State d) (M : POVM y d) (x : ι) (outcome : y) : ℝ :=
  p x * (M.prob (rho x) outcome : ℝ)

/-- Marginal probability of a measurement outcome. -/
noncomputable def outcomeProbability {ι y d : Type*}
    [Fintype ι] [Fintype y] [DecidableEq y] [Fintype d] [DecidableEq d]
    (p : ι → ℝ) (rho : ι → State d) (M : POVM y d) (outcome : y) : ℝ :=
  ∑ x : ι, jointProbability p rho M x outcome

/-- Classical mutual information `I(X:Y)` induced by the ensemble and POVM. -/
noncomputable def classicalMutualInformation {ι y d : Type*}
    [Fintype ι] [Fintype y] [DecidableEq y] [Fintype d] [DecidableEq d]
    (p : ι → ℝ) (rho : ι → State d) (M : POVM y d) : ℝ :=
  ∑ x : ι, ∑ outcome : y,
    let joint := jointProbability p rho M x outcome
    if joint = 0 then
      0
    else
      joint * log2 (joint / (p x * outcomeProbability p rho M outcome))

/-- The concrete Holevo inequality for the measured ensemble. -/
def HolevoBoundForMeasurement {ι y d : Type*}
    [Fintype ι] [Fintype y] [DecidableEq y] [Fintype d] [DecidableEq d]
    (p : ι → ℝ) (rho : ι → State d) (average : State d) (M : POVM y d) : Prop :=
  classicalMutualInformation p rho M ≤
    vonNeumannEntropyMatrix average.matrix -
      ∑ x : ι, p x * vonNeumannEntropyMatrix (rho x).matrix

end

end QITBench.HolevoBoundClassicalCapacityNQubits
